$(document).ready(function(){
	$(".playbutt").click(function(e){
		e.preventDefault();
		juke.play();
		console.log(juke.currentSong);
		$('.playbutt').hide();
		$('.pausebutt').show().css( "display", "inline-block");
	});
	$(".pausebutt").click(function(e){
		e.preventDefault();
		juke.pause();
		$('.pausebutt').hide();
		$('.playbutt').show();
	});
	$(".prevbutt").click(function(e){
		e.preventDefault();
		juke.previous();
		console.log(juke.currentSong);
	});
	$(".nextbutt").click(function(e){
		e.preventDefault();
		juke.next();
		console.log(juke.currentSong);
	});
});